export enum StorageKeys {
    USER_DATA = 'USER_ZINNIA',
    TOKEN = 'TOKEN',
    PRESENTATED = 'PRESENTATED',
    IS_ACCESS_GPS = 'IS_ACCESS_GPS ',
    USER_SEARCHED = 'USER_SEARCHED',
    ONESIGNAL = 'ONESIGNAL',
    POLICY_DATA = 'POLICY_DATA',
    REMEMBER_SESSION = 'REMEMBER_SESSION'
}